name: Code Review

# This workflow works across organizations using a PAT
# It directly checks out and runs the review script from velora-org/explore-code-review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      run_code_review:
        description: "Run GitHub Models code review?"
        required: false
        default: "false"

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  github-models-code-review:
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_code_review == 'true')
    runs-on: ubuntu-latest
    name: Run GitHub Models Code Review

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.js
            **/*.jsx
            **/*.ts
            **/*.tsx
            **/*.py
            **/*.java
          separator: " "

      - name: Checkout code review scripts from central repo
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/checkout@v4
        with:
          repository: velora-org/explore-code-review
          ref: main
          path: .code-review-scripts
          token: ${{ secrets.CENTRAL_REPO_PAT }}

      - name: Setup Node.js
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npm init -y
          npm install axios

      - name: Run GitHub Models Code Review
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          node .code-review-scripts/.github/scripts/github-models-review.mjs

      - name: Cleanup
        if: always()
        run: |
          rm -rf .code-review-scripts
